"""`init_openup.py` scaffolds and then generates, in one command.

Three governance documents — definition-of-ready.md, definition-of-done.md and
quality-gates.md — are not seeded from templates. They are generated by `render_views.py`
from the code that enforces them, because a governance document that disagrees with its
check is worse than no document: people follow the document while the machine applies the
code.

That reason is about what *produces* those files, not about when. For as long as generating
them was a second command the user had to be told to run, a project could sit in a state
where the checks exist and the documents describing them do not — and the only thing
standing between a reader and that state was their having read one more paragraph.

So init renders too, and these tests hold the three properties that makes non-obvious:

  * the documents exist after one command, not two;
  * `--no-render` still exists, because rendering needs dependencies the scaffold does not;
  * a render that cannot run reports ERROR and exits 2 rather than leaving a tree that
    looks finished. Exit 2 is "could not evaluate" in the same three-way contract every
    validator uses, so a workflow halts on its setup-fault branch.
"""

from __future__ import annotations

import json
import os
import pathlib
import subprocess
import sys

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
INIT = REPO_ROOT / "extensions" / "openup" / "scripts" / "python" / "init_openup.py"

GENERATED = (
    ".specify/governance/definition-of-ready.md",
    ".specify/governance/definition-of-done.md",
    ".specify/governance/quality-gates.md",
)

# Seeded from a template rather than generated. Present either way; listed here so a test
# can tell "init did nothing" apart from "init scaffolded but did not render".
SEEDED = ".specify/wbs/wbs.yaml"


def run_init(root: pathlib.Path, *argv: str, env: dict | None = None):
    return subprocess.run(
        [sys.executable, str(INIT), "--root", str(root), *argv],
        capture_output=True, text=True, env=env,
    )


@pytest.fixture
def broken_env(tmp_path: pathlib.Path) -> dict:
    """An environment where PyYAML cannot be imported.

    openup_model answers a missing PyYAML with SystemExit(2) at import time, which is the
    exact failure the error path has to survive: it is not an ImportError, and left uncaught
    it kills the process before the verdict is written.
    """
    blocked = tmp_path / "blocked"
    blocked.mkdir()
    (blocked / "yaml.py").write_text('raise ImportError("blocked for test")\n')
    return {**os.environ, "PYTHONPATH": str(blocked)}


def test_one_command_leaves_no_generated_document_missing(tmp_path):
    """The point of the change. Two commands meant a window where one had been run."""
    result = run_init(tmp_path)
    assert result.returncode == 0, result.stderr

    missing = [rel for rel in GENERATED if not (tmp_path / rel).is_file()]
    assert not missing, f"init did not generate {missing}"


def test_no_render_scaffolds_without_generating(tmp_path):
    """The escape hatch, and the reason it is needed: rendering pulls in jsonschema and
    referencing, which the scaffold itself does not require."""
    result = run_init(tmp_path, "--no-render")
    assert result.returncode == 0, result.stderr

    assert (tmp_path / SEEDED).is_file(), "scaffold should still be written"
    for rel in GENERATED:
        assert not (tmp_path / rel).exists(), f"{rel} should not exist under --no-render"

    assert "render_views.py --write" in result.stdout, (
        "--no-render must still name the command that completes the job"
    )


def test_no_render_survives_a_missing_dependency(tmp_path, broken_env):
    """Scaffolding on a machine with no PyYAML is legitimate and must not be blocked by a
    dependency only the rendering step needs."""
    result = run_init(tmp_path, "--no-render", env=broken_env)
    assert result.returncode == 0, result.stderr
    assert (tmp_path / SEEDED).is_file()


def test_a_render_that_cannot_run_is_an_error_not_a_pass(tmp_path, broken_env):
    """The invariant the whole project turns on: a check that could not run is never
    reported as a check that passed. Here that means exit 2, not exit 0 with three files
    quietly absent."""
    result = run_init(tmp_path, env=broken_env)

    assert result.returncode == 2, (
        f"expected exit 2 (could-not-evaluate), got {result.returncode}"
    )
    assert (tmp_path / SEEDED).is_file(), (
        "the scaffold is still written — init never overwrites, so re-running is the fix"
    )
    for rel in GENERATED:
        assert not (tmp_path / rel).exists()


@pytest.mark.parametrize("argv", [(), ("--no-render",)])
def test_json_mode_emits_a_parseable_verdict(tmp_path, argv):
    """`render_views.write_views` narrates to stdout. Under --json that narration would land
    ahead of the verdict, and a workflow step would parse '  wrote  ...' as JSON."""
    result = run_init(tmp_path, "--json", *argv)
    assert result.returncode == 0, result.stderr

    verdict = json.loads(result.stdout)
    assert verdict["status"] == "PASS"
    assert verdict["validator"] == "openup-init"


def test_json_mode_stays_parseable_when_rendering_fails(tmp_path, broken_env):
    """The failure path is the one that matters here: an unparseable verdict and a bare
    exit 2 are indistinguishable to a caller from a crash."""
    result = run_init(tmp_path, "--json", env=broken_env)
    assert result.returncode == 2

    verdict = json.loads(result.stdout)
    assert verdict["status"] == "ERROR"

    checks = {check["id"]: check["status"] for check in verdict["checks"]}
    assert checks["INIT-001"] == "PASS", "the scaffold did happen and should say so"
    assert checks["INIT-003"] == "ERROR", "the render did not, and should say that too"


def test_rerunning_preserves_authored_content(tmp_path):
    """'Generated does not mean approved' has a converse: authored content survives init.

    Re-running is the supported way to restore a store someone deleted, which only works if
    it is safe on a populated tree.
    """
    assert run_init(tmp_path).returncode == 0

    authored = tmp_path / SEEDED
    authored.write_text("# edited by a human\n")

    assert run_init(tmp_path).returncode == 0
    assert authored.read_text() == "# edited by a human\n", "init overwrote authored content"


def test_generated_documents_are_refreshed_on_a_rerun(tmp_path):
    """The converse of the test above, and the reason rendering is not simply skipped when
    the files already exist: a generated document is owned by the code, so a stale one is a
    defect rather than content to preserve. VIEW-001 fails on exactly this.
    """
    assert run_init(tmp_path).returncode == 0

    stale = tmp_path / GENERATED[0]
    stale.write_text("stale\n")

    assert run_init(tmp_path).returncode == 0
    assert stale.read_text() != "stale\n", "a generated document must be regenerated"
