#!/usr/bin/env python3
"""Scaffold the OpenUP governance tree.

Creates the directories and seeds the canonical stores from templates. Existing files are
NEVER overwritten — specup.md s31 draws the line at "generated does not mean approved", and
the converse holds too: authored content must survive re-running init.

Emits the same JSON verdict shape as the validators, so it composes into a workflow.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import shutil
import sys

EXTENSION_DIR = pathlib.Path(__file__).resolve().parent.parent.parent
TEMPLATE_DIR = EXTENSION_DIR / "templates"

DIRECTORIES = [
    ".specify/lifecycle",
    ".specify/governance",
    ".specify/architecture",
    ".specify/wbs",
    ".specify/risks",
    ".specify/traceability",
    ".specify/evidence",
]

# template file -> destination, relative to the project root.
#
# Only AUTHORED documents are seeded here. definition-of-ready.md, definition-of-done.md and
# quality-gates.md are deliberately absent: they are generated by render_views.py from the code
# that enforces them, because a governance document that disagrees with the check is worse than
# no document — people follow the document while the machine applies the code.
SEEDS = {
    "wbs-template.yaml": ".specify/wbs/wbs.yaml",
    "risk-register-template.yaml": ".specify/risks/risk-register.yaml",
    "requirements-template.yaml": ".specify/traceability/requirements.yaml",
    "traceability-template.yaml": ".specify/traceability/traceability.yaml",
    "vision-template.md": ".specify/lifecycle/vision.md",
    "stakeholders-template.md": ".specify/lifecycle/stakeholders.md",
    "change-control-template.md": ".specify/governance/change-control.md",
    "approval-matrix-template.md": ".specify/governance/approval-matrix.md",
    # s7: the operating contract. The nearest one wins, so a scoped file narrows the root.
    "agents-root-template.md": "AGENTS.md",
    "agents-specify-template.md": ".specify/AGENTS.md",
    "agents-src-template.md": "src/AGENTS.md",
}

# s9: every governed directory carries a context map, so an agent navigates
# directory -> AGENTS.md -> index.md -> the one artifact it needs (s56, s57) rather than
# loading the repository. CTX-001 checks this; seeding it is what makes the check passable.
INDEX_TEMPLATE = "index-template.md"

GENERATED_NEXT = (
    "Generated governance and view documents are not seeded. Produce them with:\n"
    "  python3 .specify/extensions/openup/scripts/python/render_views.py --write"
)


def main() -> int:
    parser = argparse.ArgumentParser(description="Scaffold the OpenUP governance tree")
    parser.add_argument("--root", default=".", help="project root (default: cwd)")
    parser.add_argument("--json", action="store_true", help="emit a JSON verdict on stdout")
    parser.add_argument("--program", default=None, help="program name to seed into the WBS root")
    args = parser.parse_args()

    root = pathlib.Path(args.root).resolve()
    if not root.is_dir():
        payload = {"validator": "openup-init", "status": "ERROR",
                   "error": f"project root does not exist: {root}"}
        print(json.dumps(payload, indent=2) if args.json else f"ERROR: {payload['error']}",
              file=sys.stdout if args.json else sys.stderr)
        return 2

    created: list[str] = []
    skipped: list[str] = []

    for relative in DIRECTORIES:
        path = root / relative
        if path.is_dir():
            skipped.append(f"{relative}/ (exists)")
        else:
            path.mkdir(parents=True, exist_ok=True)
            created.append(f"{relative}/")

    for template_name, destination in SEEDS.items():
        target = root / destination
        source = TEMPLATE_DIR / template_name
        if target.exists():
            skipped.append(f"{destination} (authored content preserved)")
            continue
        if not source.is_file():
            skipped.append(f"{destination} (no template {template_name})")
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        content = source.read_text()
        if args.program and template_name == "wbs-template.yaml":
            content = content.replace("REPLACE-WITH-PROGRAM-NAME", args.program)
        target.write_text(content)
        created.append(destination)

    # s8: capability contracts, one directory per activity. Shipped for the six activities
    # that have a validator behind them. `contracts` and `microcks` are in s8's list and are
    # deliberately absent: nothing parses a contract document (see the README's Limitations),
    # and a skill for a capability that does not exist teaches an agent to claim it.
    skills_source = TEMPLATE_DIR / "skills"
    if skills_source.is_dir():
        for skill in sorted(p for p in skills_source.iterdir() if (p / "SKILL.md").is_file()):
            target = root / "skills" / skill.name / "SKILL.md"
            if target.exists():
                skipped.append(f"skills/{skill.name}/SKILL.md (authored content preserved)")
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text((skill / "SKILL.md").read_text())
            created.append(f"skills/{skill.name}/SKILL.md")

    index_source = TEMPLATE_DIR / INDEX_TEMPLATE
    if index_source.is_file():
        for relative in DIRECTORIES:
            target = root / relative / "index.md"
            if target.exists():
                skipped.append(f"{relative}/index.md (exists)")
                continue
            target.write_text(index_source.read_text())
            created.append(f"{relative}/index.md")

    config_target = root / ".specify" / "extensions" / "openup" / "openup-config.yml"
    if not config_target.exists():
        source = EXTENSION_DIR / "openup-config.yml"
        if source.is_file():
            config_target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, config_target)
            created.append(str(config_target.relative_to(root)))
    else:
        skipped.append(".specify/extensions/openup/openup-config.yml (exists)")

    verdict = {
        "validator": "openup-init",
        "status": "PASS",
        "checks": [
            {"id": "INIT-001", "status": "PASS",
             "message": f"{len(created)} path(s) created", "evidence": created},
            {"id": "INIT-002", "status": "PASS",
             "message": f"{len(skipped)} path(s) left untouched", "evidence": skipped},
        ],
        "metrics": {"created": len(created), "skipped": len(skipped)},
    }

    if args.json:
        print(json.dumps(verdict, indent=2))
    else:
        print("OpenUP governance tree")
        print("=" * 22)
        for item in created:
            print(f"  created  {item}")
        for item in skipped:
            print(f"  kept     {item}")
        print(f"\n  {len(created)} created, {len(skipped)} preserved")
        print(f"\n{GENERATED_NEXT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
