#!/usr/bin/env python3
"""Scaffold the OpenUP governance tree.

Creates the directories and seeds the canonical stores from templates. Existing files are
NEVER overwritten — specup.md s31 draws the line at "generated does not mean approved", and
the converse holds too: authored content must survive re-running init.

Emits the same JSON verdict shape as the validators, so it composes into a workflow.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import pathlib
import shutil
import sys

EXTENSION_DIR = pathlib.Path(__file__).resolve().parent.parent.parent
TEMPLATE_DIR = EXTENSION_DIR / "templates"

DIRECTORIES = [
    ".specify/lifecycle",
    ".specify/governance",
    ".specify/architecture",
    ".specify/wbs",
    ".specify/risks",
    ".specify/traceability",
    ".specify/evidence",
]

# template file -> destination, relative to the project root.
#
# Only AUTHORED documents are seeded here. definition-of-ready.md, definition-of-done.md and
# quality-gates.md are deliberately absent: they are generated by render_views.py from the code
# that enforces them, because a governance document that disagrees with the check is worse than
# no document — people follow the document while the machine applies the code.
SEEDS = {
    "wbs-template.yaml": ".specify/wbs/wbs.yaml",
    "risk-register-template.yaml": ".specify/risks/risk-register.yaml",
    "requirements-template.yaml": ".specify/traceability/requirements.yaml",
    "traceability-template.yaml": ".specify/traceability/traceability.yaml",
    "vision-template.md": ".specify/lifecycle/vision.md",
    "stakeholders-template.md": ".specify/lifecycle/stakeholders.md",
    "change-control-template.md": ".specify/governance/change-control.md",
    "approval-matrix-template.md": ".specify/governance/approval-matrix.md",
    # Seeded with their template names intact, which is the point. `architecture_baselined`
    # checks only that `.specify/architecture/architecture.md` EXISTS, so seeding a blank one
    # would retire the gate's first condition on day one while the document still said nothing.
    # Left as templates, the gate keeps reporting "no architecture document found" until
    # somebody writes one, and the author has somewhere to start. The ADR template is copied
    # per decision, so it stays a template permanently.
    "architecture-template.md": ".specify/architecture/architecture-template.md",
    "adr-template.md": ".specify/architecture/adr-template.md",
    # The trust root APV-002 verifies a signed approval commit against. Seeded empty of keys
    # and full of reasoning: a project that never adds a signer gets warned by APV-004 rather
    # than silently trusting nobody, and the file explains why it is version-controlled.
    "allowed-signers-template.txt": ".specify/governance/allowed-signers",
    # The three standards the agent operating contract binds it to. Seeded rather than read
    # out of the extension directory on purpose: a project may amend a rule, and a rule it
    # cannot amend is one it will work around instead. The amendment is then a visible diff
    # under change control, which is the outcome worth having.
    "language-rules-template.md": ".specify/governance/language-rules.md",
    "coding-rules-template.md": ".specify/governance/coding-rules.md",
    "security-practices-template.md": ".specify/governance/security-practices.md",
    # s7: the operating contract. The nearest one wins, so a scoped file narrows the root.
    "agents-root-template.md": "AGENTS.md",
    "agents-specify-template.md": ".specify/AGENTS.md",
    "agents-src-template.md": "src/AGENTS.md",
}

# s9: every governed directory carries a context map, so an agent navigates
# directory -> AGENTS.md -> index.md -> the one artifact it needs (s56, s57) rather than
# loading the repository. CTX-001 checks this; seeding it is what makes the check passable.
INDEX_TEMPLATE = "index-template.md"

GENERATED_NEXT = (
    "Generated governance and view documents are not seeded. Produce them with:\n"
    "  python3 .specify/extensions/openup/scripts/python/render_views.py --write"
)


def _render(root: pathlib.Path, json_mode: bool) -> tuple[str, str]:
    """Generate the documents this script deliberately does not seed.

    definition-of-ready.md, definition-of-done.md and quality-gates.md are produced from the
    code that enforces them, because a governance document disagreeing with its check is worse
    than no document — people follow the document while the machine applies the code. That
    reason is about what *produces* them, not about when, so running it here changes nothing
    about the guarantee and removes a step a reader had to be told to take.

    Imported lazily and on purpose. render_views needs jsonschema and referencing; the scaffold
    itself needs neither, so `--no-render` still works on a machine that has only PyYAML.
    """
    # SystemExit is caught deliberately, and is not defensive padding: openup_model reports a
    # missing PyYAML by printing to stderr and raising SystemExit(2) at import time. Letting
    # that through would kill this process before the verdict is written, so `--json` would
    # exit 2 with empty stdout — a workflow step consuming the verdict would see malformed
    # output rather than a check it can read. Converting it to an INIT-003 ERROR keeps the
    # exit code and gives the caller something to parse.
    try:
        import render_views
        from openup_model import GraphError
    except ImportError as exc:  # pragma: no cover - requires a broken install to reach
        return "ERROR", f"render_views could not be imported: {exc}"
    except SystemExit as exc:
        return "ERROR", f"a dependency render_views needs is missing (exit {exc.code})"

    # write_views narrates to stdout. Under --json that would land ahead of the verdict and
    # leave the caller parsing "  wrote  ..." as JSON, so the narration goes to stderr instead
    # of being thrown away — the operator still sees which documents were written.
    sink = contextlib.redirect_stdout(sys.stderr) if json_mode else contextlib.nullcontext()
    try:
        with sink:
            render_views.write_views(argparse.Namespace(root=str(root)))
    except GraphError as exc:
        return "ERROR", str(exc)
    except SystemExit as exc:
        return "ERROR", f"rendering stopped with exit {exc.code}"
    return "PASS", "generated governance and view documents written"


def main() -> int:
    parser = argparse.ArgumentParser(description="Scaffold the OpenUP governance tree")
    parser.add_argument("--root", default=".", help="project root (default: cwd)")
    parser.add_argument("--json", action="store_true", help="emit a JSON verdict on stdout")
    parser.add_argument("--program", default=None, help="program name to seed into the WBS root")
    parser.add_argument(
        "--no-render", action="store_true",
        help="scaffold only; do not generate the documents render_views.py produces",
    )
    args = parser.parse_args()

    root = pathlib.Path(args.root).resolve()
    if not root.is_dir():
        payload = {"validator": "openup-init", "status": "ERROR",
                   "error": f"project root does not exist: {root}"}
        print(json.dumps(payload, indent=2) if args.json else f"ERROR: {payload['error']}",
              file=sys.stdout if args.json else sys.stderr)
        return 2

    created: list[str] = []
    skipped: list[str] = []

    for relative in DIRECTORIES:
        path = root / relative
        if path.is_dir():
            skipped.append(f"{relative}/ (exists)")
        else:
            path.mkdir(parents=True, exist_ok=True)
            created.append(f"{relative}/")

    for template_name, destination in SEEDS.items():
        target = root / destination
        source = TEMPLATE_DIR / template_name
        if target.exists():
            skipped.append(f"{destination} (authored content preserved)")
            continue
        if not source.is_file():
            skipped.append(f"{destination} (no template {template_name})")
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        content = source.read_text()
        if args.program and template_name == "wbs-template.yaml":
            content = content.replace("REPLACE-WITH-PROGRAM-NAME", args.program)
        target.write_text(content)
        created.append(destination)

    # s8: capability contracts, one directory per activity. Shipped for the six activities
    # that have a validator behind them. `contracts` and `microcks` are in s8's list and are
    # deliberately absent: nothing parses a contract document (see the README's Limitations),
    # and a skill for a capability that does not exist teaches an agent to claim it.
    skills_source = TEMPLATE_DIR / "skills"
    if skills_source.is_dir():
        for skill in sorted(p for p in skills_source.iterdir() if (p / "SKILL.md").is_file()):
            target = root / "skills" / skill.name / "SKILL.md"
            if target.exists():
                skipped.append(f"skills/{skill.name}/SKILL.md (authored content preserved)")
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text((skill / "SKILL.md").read_text())
            created.append(f"skills/{skill.name}/SKILL.md")

    index_source = TEMPLATE_DIR / INDEX_TEMPLATE
    if index_source.is_file():
        for relative in DIRECTORIES:
            target = root / relative / "index.md"
            if target.exists():
                skipped.append(f"{relative}/index.md (exists)")
                continue
            target.write_text(index_source.read_text())
            created.append(f"{relative}/index.md")

    config_target = root / ".specify" / "extensions" / "openup" / "openup-config.yml"
    if not config_target.exists():
        source = EXTENSION_DIR / "openup-config.yml"
        if source.is_file():
            config_target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, config_target)
            created.append(str(config_target.relative_to(root)))
    else:
        skipped.append(".specify/extensions/openup/openup-config.yml (exists)")

    # The scaffold is written either way. Reporting happens after rendering so that a render
    # failure can carry the whole verdict to ERROR rather than being appended to a PASS.
    if not args.json:
        print("OpenUP governance tree")
        print("=" * 22)
        for item in created:
            print(f"  created  {item}")
        for item in skipped:
            print(f"  kept     {item}")
        print(f"\n  {len(created)} created, {len(skipped)} preserved\n")

    if args.no_render:
        render_status, render_message = "SKIP", "rendering skipped (--no-render)"
    else:
        render_status, render_message = _render(root, args.json)

    verdict = {
        "validator": "openup-init",
        "status": "ERROR" if render_status == "ERROR" else "PASS",
        "checks": [
            {"id": "INIT-001", "status": "PASS",
             "message": f"{len(created)} path(s) created", "evidence": created},
            {"id": "INIT-002", "status": "PASS",
             "message": f"{len(skipped)} path(s) left untouched", "evidence": skipped},
            {"id": "INIT-003", "status": render_status, "message": render_message},
        ],
        "metrics": {"created": len(created), "skipped": len(skipped)},
    }

    if args.json:
        print(json.dumps(verdict, indent=2))
    elif args.no_render:
        print(GENERATED_NEXT)

    if render_status == "ERROR":
        # The scaffold stands and re-running is safe, so the only thing missing is the three
        # generated documents. That is a setup fault, not a governance failure: exit 2, the
        # same code every validator uses for "could not evaluate", so a workflow halts on its
        # setup-fault branch instead of proceeding with a tree that is quietly incomplete.
        if not args.json:
            print(f"\nERROR: {render_message}", file=sys.stderr)
            print("The scaffold is written. Re-run this command once the dependencies are "
                  "installed, or pass --no-render to skip generation.", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
