#!/usr/bin/env python3
"""Generate the Markdown views from the canonical YAML.

specup.md s47 exists to stop humans maintaining duplicated artifacts, and s65 says plainly:
"Do not manually maintain traceability documents. Generate traceability views from structured
relationships." Until this script, three commands asked *the agent* to regenerate wbs.md,
risk-register.md, traceability.md and coverage.md by hand — manual maintenance with an extra
failure mode, since an LLM transcribing YAML into Markdown is non-deterministic, unreviewable
(every regeneration is a fresh diff) and free to disagree with the canonical data.

Two of the governance documents are generated here for the same reason: a Definition of Ready
that disagrees with select_work.py, or a gate description that overstates what evaluate_gate.py
checks, is worse than no document at all — people read the document while the machine applies
the code.

    render_views.py            report which views are missing or stale (exit 1 if any are)
    render_views.py --write    regenerate them all

No view carries a timestamp. A generated_at line would make every file differ from the one on
disk on every run, which would turn the staleness check into noise and train people to ignore it.
"""

from __future__ import annotations

import sys
from typing import Any, Callable

import evaluate_gate
import select_work
import validate_done
import validate_risk
import validate_trace
import validate_wbs
from openup_model import GraphError, Verdict, base_parser, load_graph, run, wbs_level

BANNER = "<!-- GENERATED by render_views.py — do not edit. Regenerate with: render_views.py --write -->"

RENDERERS: dict[str, Callable[[Any, dict], str]] = {}


def view(path: str):
    def register(fn):
        RENDERERS[path] = fn
        return fn
    return register


def _page(title: str, source: str, *blocks: str) -> str:
    """Every view opens the same way: what it is, and what it was generated from."""
    head = [BANNER, "", f"# {title}", "", f"*Generated from `{source}`. Edit the source, not this file.*", ""]
    return "\n".join(head + list(blocks)).rstrip() + "\n"


def _cell(value: Any) -> str:
    """Render a value for a Markdown table cell, keeping a pipe from breaking the row."""
    if value is None or value == [] or value == {}:
        return "—"
    if isinstance(value, list):
        return ", ".join(f"`{item}`" for item in value)
    return str(value).replace("|", "\\|")


# --------------------------------------------------------------------------
# Work breakdown
# --------------------------------------------------------------------------


@view(".specify/wbs/wbs.md")
def _wbs(graph, config) -> str:
    if not graph.wbs:
        return _page("Work Breakdown Structure", ".specify/wbs/wbs.yaml", "_No WBS nodes._")

    # A nested list, not an indented table: the WBS is a tree, and a list renders as one both
    # in Markdown and in the raw file. Table cells padded with &nbsp; do neither.
    rows = []
    for node_id in sorted(graph.wbs, key=lambda n: [int(s) for s in n[len("WBS-"):].split(".")]):
        node = graph.wbs[node_id]
        level = wbs_level(node_id)
        facts = [f"*L{level} {validate_wbs.LEVEL_NAMES.get(level, '?')}*"]
        facts += [str(node[key]) for key in ("kind", "owner", "iteration", "status") if node.get(key)]
        line = f"{'  ' * (level - 1)}- **`{node_id}`** {node.get('name', '')} — {' · '.join(facts)}"
        links = [f"{label} {_cell(node.get(key))}"
                 for key, label in (("requirements", "implements"), ("risks", "mitigates"),
                                    ("acceptance", "covers"), ("evidence", "evidenced by"))
                 if node.get(key)]
        if links:
            line += f"<br>\n{'  ' * (level - 1)}  {'; '.join(links)}"
        rows.append(line)

    # Early termination is a deliberate, declared exception to the seven-level model. It has
    # to be visible in the view, or the reason for the exception lives only in the YAML.
    terminal = [f"- `{nid}` — {node['terminal_reason']}"
                for nid, node in sorted(graph.wbs.items()) if node.get("terminal_reason")]
    blocks = ["\n".join(rows), ""]
    if terminal:
        blocks += [f"## Declared early termination ({config['wbs'].get('depth_policy', 'semantic')} policy)",
                   "", "\n".join(terminal), ""]

    program = graph.wbs_doc.get("program")
    return _page(f"Work Breakdown Structure — {program}" if program else "Work Breakdown Structure",
                 ".specify/wbs/wbs.yaml", *blocks)


# --------------------------------------------------------------------------
# Risks
# --------------------------------------------------------------------------


@view(".specify/risks/risk-register.md")
def _risks(graph, config) -> str:
    if not graph.risks:
        return _page("Risk Register", ".specify/risks/risk-register.yaml", "_No risks registered._")

    high = config["risk"].get("high_exposure_threshold", 0.40)
    critical = config["risk"].get("critical_exposure_threshold", 0.65)

    def exposure(risk: dict) -> float:
        return risk.get("probability", 0) * risk.get("impact", 0)

    rows = ["| Risk | Exposure | P × I | Status | Owner | Mitigation | Verification | Residual |",
            "|---|---|---|---|---|---|---|---|"]
    for risk_id, risk in sorted(graph.risks.items(), key=lambda kv: -exposure(kv[1])):
        value = exposure(risk)
        band = "🔴 critical" if value >= critical else "🟠 high" if value >= high else "🟡 moderate"
        rows.append(
            f"| `{risk_id}` {_cell(risk.get('title'))} | {value:.2f} {band} "
            f"| {risk.get('probability', 0)} × {risk.get('impact', 0)} "
            f"| {_cell(risk.get('status'))} | {_cell(risk.get('owner'))} "
            f"| {_cell(risk.get('mitigation'))} | {_cell(risk.get('verification'))} "
            f"| {risk.get('residual_exposure', '—')} |"
        )

    return _page("Risk Register", ".specify/risks/risk-register.yaml",
                 "\n".join(rows), "",
                 f"Thresholds: high ≥ {high:.2f}, critical ≥ {critical:.2f} "
                 f"(`openup-config.yml`, `risk.*_exposure_threshold`). Exposure is "
                 f"probability × impact and is recomputed by `validate_risk.py`; a hand-edited "
                 f"`exposure:` field fails `RISK-001`.")


# --------------------------------------------------------------------------
# Traceability
# --------------------------------------------------------------------------


@view(".specify/traceability/traceability.md")
def _traceability(graph, config) -> str:
    if not graph.edges:
        return _page("Traceability Graph", "the configured traceability stores", "_No edges._")

    blocks: list[str] = []
    by_relation: dict[str, list] = {}
    for edge in graph.edges:
        by_relation.setdefault(edge.relation, []).append(edge)

    for relation in sorted(by_relation):
        rows = ["| From | To | Provenance | Status | Declared in |", "|---|---|---|---|---|"]
        for edge in sorted(by_relation[relation], key=lambda e: (e.from_id, e.to_id)):
            if edge.provenance == "derived":
                mark = f"derived (`{edge.derived_by}`)"
            elif edge.provenance == "approved":
                mark = f"approved ({_cell((edge.approval or {}).get('by'))})"
            else:
                mark = "asserted"
            rows.append(
                f"| `{edge.from_id}` | `{edge.to_id}` | {mark} "
                f"| {_cell(edge.status)} | `{_cell(edge.source_file)}` |"
            )
        blocks += [f"## {relation} ({len(by_relation[relation])})", "", "\n".join(rows), ""]

    return _page("Traceability Graph", "the configured traceability stores",
                 f"Inverses are derived at load time and never stored, so each edge appears "
                 f"once, in active voice. {len(graph.edges)} edge(s) across "
                 f"{len(graph.raw_stores)} store(s).", "", *blocks)


@view(".specify/traceability/coverage.md")
def _coverage(graph, config) -> str:
    class _Args:
        root = str(graph.root)
        json = False

    metrics = validate_trace.validate(_Args()).metrics
    thresholds = config["traceability"]["coverage_thresholds"]
    edges = metrics.get("edges", 0) or 1

    def pct(key: str) -> str:
        return f"{metrics.get(key, 0):.0%}"

    coverage = [
        "| Metric | Value | Threshold |", "|---|---|---|",
        f"| Requirement → implementation | {pct('forward_coverage')} | {thresholds.get('forward', 1.0):.0%} |",
        f"| Requirement → verification | {pct('verification_coverage')} | {thresholds.get('forward', 1.0):.0%} |",
        f"| Source → requirement (backward) | {pct('backward_coverage')} | {thresholds.get('backward', 0.95):.0%} |",
        f"| Acceptance criterion → scenario | {pct('scenario_coverage')} | 100% |",
        f"| Source → test | {pct('code_test_coverage')} | reported, not gated |",
    ]

    class _RiskArgs:
        root = str(graph.root)
        json = False

    risk_metrics = validate_risk.validate(_RiskArgs()).metrics
    coverage += [
        f"| Open risk → mitigation | {risk_metrics.get('mitigation_coverage', 0):.0%} | 100% for high exposure |",
        f"| Open risk → evidence | {risk_metrics.get('evidence_coverage', 0):.0%} | reported, not gated |",
    ]

    # The provenance mix belongs here and not only in the audit: a coverage figure built from
    # unverifiable claims is not coverage, and speckit.openup.trace.md promises the mix on
    # this page. Both signed labels are split into what survives a re-check and what does not.
    reproduced = metrics.get("derived_verified", 0)
    unreproduced = metrics.get("derived_unverified", 0)
    approved = metrics.get("approved_verified", 0)
    stale = metrics.get("approved_stale", 0)
    asserted = metrics.get("provenance_mix", {}).get("asserted", 0)
    verifiable = (reproduced + approved) / edges

    mix = [
        "| Provenance | Edges | Share | What it is worth |", "|---|---|---|---|",
        f"| derived, reproduced | {reproduced} | {reproduced / edges:.0%} | A rule re-ran and produced it (TRC-010) |",
        f"| derived, unreproduced | {unreproduced} | {unreproduced / edges:.0%} | Names a rule that is not implemented — **not evidence** |",
        f"| approved, current | {approved} | {approved / edges:.0%} | Signed off, and still matching what was signed (TRC-013) |",
        f"| approved, stale | {stale} | {stale / edges:.0%} | Approved for content that has since changed — **not evidence** |",
        f"| asserted | {asserted} | {asserted / edges:.0%} | An agent or author claim only |",
    ]

    return _page("Traceability Coverage", "validate_trace.py",
                 "## Coverage", "", "\n".join(coverage), "",
                 "## Evidence quality", "", "\n".join(mix), "",
                 f"**{verifiable:.0%} of edges are independently verifiable.** That is the "
                 f"figure `traceability_final` scores at the release gate, and it counts only "
                 f"the two rows a third party could check without taking anyone's word for it. "
                 f"A graph can be 100% covered and still prove very little.")


# --------------------------------------------------------------------------
# Governance documents
# --------------------------------------------------------------------------


@view(".specify/governance/definition-of-ready.md")
def _definition_of_ready(graph, config) -> str:
    rows = ["| # | A task is ready when… |", "|---|---|"]
    rows += [f"| `{rule}` | {text} |" for rule, text in select_work.READINESS_RULES.items()]
    return _page("Definition of Ready", "select_work.py",
                 "\n".join(rows), "",
                 "These are applied, not advised. `select_work.py` refuses to return a task "
                 "that fails any of them, and each refusal is tagged with the rule id above:",
                 "", "```bash",
                 "python3 .specify/extensions/openup/scripts/python/select_work.py --json",
                 "```", "",
                 "A task that is not ready is not blocked forever — it is blocked until the "
                 "missing link exists. The reasons are the work.")


@view(".specify/governance/definition-of-done.md")
def _definition_of_done(graph, config) -> str:
    rows = ["| # | A task is done when… |", "|---|---|"]
    rows += [f"| `{rule}` | {text} |" for rule, text in validate_done.DONE_RULES.items()]
    return _page("Definition of Done", "validate_done.py",
                 "\n".join(rows), "",
                 "s29 asks for `status: done` to be *a computed governance state rather than a "
                 "casual AI declaration*. These are the computations:",
                 "", "```bash",
                 "python3 .specify/extensions/openup/scripts/python/validate_done.py --json",
                 "```", "",
                 "Two of s29's clauses are missing on purpose. Contract tests and Microcks "
                 "conformance have nothing behind them yet (see the project README's "
                 "Limitations), and a check that cannot fail is worse than a missing one — it "
                 "reports compliance it never established.", "",
                 "A node marked `done` that fails any row above is not done. Carrying work into "
                 "the next iteration is normal; a green board that does not match the "
                 "repository is not.")


@view(".specify/governance/quality-gates.md")
def _quality_gates(graph, config) -> str:
    gates = config.get("gates", {})
    if not gates:
        return _page("Quality Gates", "openup-config.yml", "_No gates configured._")

    blocks: list[str] = []
    for name, spec in gates.items():
        rows = ["| Condition | What it checks |", "|---|---|"]
        for condition_name in spec.get("conditions", []):
            description = evaluate_gate.DESCRIPTIONS.get(
                condition_name,
                "**Not implemented.** A condition named here but absent from evaluate_gate.py "
                "fails the gate closed.",
            )
            rows.append(f"| `{condition_name}` | {description} |")
        blocks += [f"## {name}", "", f"Phase: **{spec.get('phase', '—')}**", "",
                   "\n".join(rows), ""]

    return _page("Quality Gates", "openup-config.yml",
                 "Every condition below is a named predicate implemented in "
                 "`evaluate_gate.py`, from which these descriptions are taken. A gate "
                 "passes only if all of its conditions pass; absence of evidence fails a "
                 "condition rather than skipping it.", "", "```bash",
                 "python3 .specify/extensions/openup/scripts/python/evaluate_gate.py "
                 "--gate GATE-LIFECYCLE_ARCHITECTURE --json", "```", "", *blocks)


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------


def render_all(graph, config) -> dict[str, str]:
    return {path: renderer(graph, config) for path, renderer in sorted(RENDERERS.items())}


def write_views(args) -> int:
    graph, config = load_graph(args.root)
    written, unchanged = [], []
    for relative, content in render_all(graph, config).items():
        target = graph.root / relative
        if target.is_file() and target.read_text() == content:
            unchanged.append(relative)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        written.append(relative)

    for relative in written:
        print(f"  wrote      {relative}")
    for relative in unchanged:
        print(f"  unchanged  {relative}")
    print(f"\n{len(written)} view(s) regenerated, {len(unchanged)} already current")
    return 0


def validate(args) -> Verdict:
    graph, config = load_graph(args.root)
    verdict = Verdict("render-views")

    problems: list[str] = []
    for relative, content in render_all(graph, config).items():
        target = graph.root / relative
        if not target.is_file():
            problems.append(f"{relative}: missing — run render_views.py --write")
        elif target.read_text() != content:
            problems.append(f"{relative}: stale — the canonical source has moved on, or the "
                            f"file was hand-edited")
    if problems:
        verdict.fail("VIEW-001", f"{len(problems)} view(s) missing or stale", problems)
    else:
        verdict.ok("VIEW-001", f"all {len(RENDERERS)} generated view(s) match their sources")

    # A .md sitting beside a canonical store that no renderer owns is either a stale view from
    # an earlier layout or a hand-written document in a generated place. WARN: it may be
    # deliberate, and deleting someone's document is not this script's call.
    owned = set(RENDERERS)
    strays = [
        f"{rel}: carries the generated banner but no renderer owns it"
        for rel in sorted(
            str(p.relative_to(graph.root))
            for directory in (".specify/wbs", ".specify/risks", ".specify/traceability",
                              ".specify/governance")
            for p in (graph.root / directory).glob("*.md") if p.is_file()
        )
        if rel not in owned and BANNER.split(" — ")[0] in (graph.root / rel).read_text()
    ]
    if strays:
        verdict.warn("VIEW-002", f"{len(strays)} generated file(s) with no source", strays)
    else:
        verdict.ok("VIEW-002", "no generated view is left without a source")

    verdict.metrics = {"views": len(RENDERERS), "stale_or_missing": len(problems),
                       "orphaned": len(strays)}
    return verdict


def main() -> int:
    parser = base_parser(__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true",
                        help="regenerate every view instead of reporting on it")
    if "--write" in sys.argv[1:]:
        args = parser.parse_args()
        try:
            return write_views(args)
        except GraphError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
    return run(validate, parser)


if __name__ == "__main__":
    sys.exit(main())
